/* Styles are pure data: parts reference instruments by id and describe
   patterns in the step DSL (one char per step; length = beatsPerBar ×
   stepsPerBeat). Uppercase = accent. Adding a tune touches nothing else. */

export const DRUM_MAPS = {
  celtic: {D:['bodhran','dum',1], d:['bodhran','dum',.55], T:['bodhran','tek',.95], t:['bodhran','tek',.5]},
  darbuka: {D:['darbuka','dum',1], d:['darbuka','dum',.55], T:['darbuka','tek',.95], t:['darbuka','tek',.5], K:['darbuka','ka',.6], k:['darbuka','ka',.35]},
  shanty: {S:['crowd','stomp',1], s:['crowd','stomp',.5], C:['crowd','clap',.95], c:['crowd','clap',.5], D:['bodhran','dum',.9], d:['bodhran','dum',.5], T:['bodhran','tek',.9], t:['bodhran','tek',.5]},
  march: {S:['crowd','stomp',1], s:['crowd','stomp',.5], D:['bodhran','dum',.9], d:['bodhran','dum',.55], T:['bodhran','tek',.9], t:['bodhran','tek',.5]},
};

export const STYLES = {
  tavern_jig: {
    name: 'Tavern Jig', icon: '🍺', mode: 'dorian', tonic: 2, bpm: 108,
    beatsPerBar: 2, stepsPerBeat: 6, swing: 0, lilt: .07, reverb: .14, drone: .4, pad: 0,
    sections: {A: [{d:0,q:'m'},{d:3,q:'M'},{d:0,q:'m'},{d:6,q:'M'}],
               B: [{d:2,q:'M'},{d:6,q:'M'},{d:0,q:'m'},{d:6,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D.....D.....',w:2},{s:'D.....d...t.',w:1}],
              lively: [{s:'D.t.t.D.t.t.',w:3},{s:'D...t.D.t.t.',w:1},{s:'D.ttt.D.t.t.',w:2},{s:'D.t.t.D.ttt.',w:1}],
              rowdy: [{s:'D.t.t.D.t.t.',w:3},{s:'D.t.t.D.ttt.',w:1},{s:'D.ttt.D.t.t.',w:1}]},
        fills: ['D...t.dtdtdt','D.t.t.D.dtdt','D.ttt.D.t.tt']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.55},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      jingle: {kind:'jingle', inst:'tambourine', pat:{lively:[{s:'x.....X.....',w:1}], rowdy:[{s:'X.....X.....',w:2},{s:'X..x..X..x..',w:1}]}},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C...........',w:2},{s:'0.1.2.3.2.1.',w:1}],
              lively: [{s:'C.1.2.u.1.2.',w:3},{s:'C.1.3.2.4.2.',w:2},{s:'C.....u.1.2.',w:1}],
              rowdy: [{s:'C.1.2.C.1.2.',w:2},{s:'C.1.3.u.2.4.',w:1},{s:'C.1.2.u.3.2.',w:2}]},
        fills: ['0.1.2.3.4.5.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...........',w:1}],
              lively: [{s:'R.....5.....',w:2},{s:'R.....5...P.',w:1}],
              rowdy: [{s:'R.....5.R...',w:1},{s:'R.....5...P.',w:1}]}},
    }},
  festival_jig: {
    name: 'Festival Jig', icon: '🎉', mode: 'major', tonic: 0, bpm: 116,
    beatsPerBar: 2, stepsPerBeat: 6, swing: 0, lilt: .06, reverb: .16, drone: .3, pad: 0,
    sections: {A: [{d:0,q:'M'},{d:3,q:'M'},{d:0,q:'M'},{d:4,q:'M'}],
               B: [{d:3,q:'M'},{d:0,q:'M'},{d:4,q:'M'},{d:0,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D.....D.....',w:2},{s:'D.....d...t.',w:1}],
              lively: [{s:'D.t.t.D.t.t.',w:3},{s:'D.ttt.D.t.t.',w:2},{s:'D.t.t.D.ttt.',w:1}],
              rowdy: [{s:'D.t.t.D.t.t.',w:2},{s:'D.ttt.D.ttt.',w:1},{s:'D.t.t.D.ttt.',w:1}]},
        fills: ['D.t.t.dtdtdt','D.ttt.D.t.tt']},
      claps: {kind:'drum', map:'shanty',
        pat: {rowdy: [{s:'......C.....',w:1}]}},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.6},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      jingle: {kind:'jingle', inst:'tambourine', pat:{lively:[{s:'x.....X.....',w:1}], rowdy:[{s:'X.....X.....',w:1}]}},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C...........',w:2},{s:'0.1.2.3.2.1.',w:1}],
              lively: [{s:'C.1.2.u.1.2.',w:3},{s:'C.1.2.C.1.2.',w:2},{s:'C.1.3.2.4.2.',w:1}],
              rowdy: [{s:'C.1.2.C.1.2.',w:3},{s:'C.1.2.u.3.2.',w:1}]},
        fills: ['0.1.2.3.4.5.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...........',w:1}],
              lively: [{s:'R.....5.....',w:2},{s:'R.....5...P.',w:2}],
              rowdy: [{s:'R.....5.R...',w:1},{s:'R.....5...P.',w:1}]}},
    }},
  kerry_polka: {
    /* Gaelic recast per research: no thirds anywhere (DADGAD ambiguity),
       double-tonic vamp, ONE idiomatic bodhrán pattern (down-up down down) */
    name: 'Céilí Dance', icon: '🍀', mode: 'mixolydian', tonic: 9, bpm: 132,
    beatsPerBar: 2, stepsPerBeat: 4, swing: .1, reverb: .13, drone: .35, pad: 0,
    sections: {A: [{d:0,q:'5'},{d:0,q:'5'},{d:6,q:'5'},{d:0,q:'5'}],
               B: [{d:3,q:'5'},{d:0,q:'5'},{d:6,q:'5'},{d:0,q:'5'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D...D...',w:1}],
              lively: [{s:'D.t.D.d.',w:1}],
              rowdy: [{s:'D.t.D.d.',w:1}]},
        fills: ['D.t.dtdt']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.5},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      jingle: {kind:'jingle', inst:'tambourine', pat:{lively:[{s:'..x...x.',w:1}], rowdy:[{s:'..X...X.',w:1}]}},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C.......',w:2},{s:'B...c...',w:1}],
              lively: [{s:'B.c.B.c.',w:3},{s:'C.c.B.c.',w:2},{s:'B.c.C.c.',w:1}],
              rowdy: [{s:'B.c.B.c.',w:2},{s:'C.c.C.c.',w:1}]},
        fills: ['B.c.0123']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R.......',w:1}],
              lively: [{s:'R...5...',w:2},{s:'R...5..P',w:1}],
              rowdy: [{s:'R...5..P',w:1},{s:'R.R.5...',w:1}]}},
    }},
  slip_jig: {
    name: 'Slip Jig', icon: '🦋', mode: 'dorian', tonic: 4, bpm: 96,
    beatsPerBar: 3, stepsPerBeat: 6, swing: 0, lilt: .07, reverb: .16, drone: .38, pad: 0,
    sections: {A: [{d:0,q:'m'},{d:0,q:'m'},{d:6,q:'M'},{d:6,q:'M'}],
               B: [{d:3,q:'M'},{d:6,q:'M'},{d:0,q:'m'},{d:0,q:'m'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D.....d.....d.....',w:2},{s:'D.................',w:1}],
              lively: [{s:'D.....d.t.t.D.t.t.',w:3},{s:'D.t.t.d.t.t.D.t.t.',w:2},{s:'D.....D.t.t.d.t.t.',w:1}],
              rowdy: [{s:'D.t.t.D.t.t.D.t.t.',w:3},{s:'D.t.t.D.t.t.D.ttt.',w:1},{s:'D.ttt.D.t.t.D.t.t.',w:1}]},
        fills: ['D.....d.t.t.dtdtdt','D.t.t.D.t.t.ttt.t.']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.5},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      jingle: {kind:'jingle', inst:'tambourine', pat:{lively:[{s:'x.....X.....x.....',w:1}], rowdy:[{s:'X.....X.....X.....',w:1}]}},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C.................',w:2},{s:'0.1.2.3.4.3.2.1.0.',w:1}],
              lively: [{s:'C.1.2.u.1.2.u.3.2.',w:3},{s:'C.1.3.2.4.2.u.1.2.',w:2},{s:'C.....u.1.2.u.3.2.',w:1}],
              rowdy: [{s:'C.1.2.C.1.2.u.3.2.',w:2},{s:'C.1.3.u.2.4.C.1.2.',w:1}]},
        fills: ['0.1.2.3.4.5.4.3.2.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R.................',w:1}],
              lively: [{s:'R.....5.....5.....',w:2},{s:'R...........5.....',w:1}],
              rowdy: [{s:'R.....5.....R....P',w:1},{s:'R.....5.....5.....',w:1}]}},
    }},
  heroes_reel: {
    name: 'Heroes’ Reel', icon: '⚔️', mode: 'mixolydian', tonic: 2, bpm: 104,
    beatsPerBar: 4, stepsPerBeat: 4, swing: .12, reverb: .12, drone: .35, pad: 0,
    sections: {A: [{d:0,q:'M'},{d:0,q:'M'},{d:6,q:'M'},{d:0,q:'M'}],
               B: [{d:3,q:'M'},{d:4,q:'m'},{d:6,q:'M'},{d:0,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D.......D...t...',w:1},{s:'D...t...d.......',w:1}],
              lively: [{s:'D.t.t.d.D.t.t.d.',w:3},{s:'D.t.t.d.D.t.D.d.',w:2},{s:'D...t.d.D.t.t.d.',w:1}],
              rowdy: [{s:'D.t.t.d.D.t.t.d.',w:3},{s:'D.t.t.dtD.t.t.d.',w:1},{s:'D.d.t.d.D.t.t.d.',w:1}]},
        fills: ['D.t.t.d.D.t.dtdt','D.t.t.d.D.d.t.t.']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.6},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      jingle: {kind:'jingle', inst:'tambourine', pat:{rowdy:[{s:'x.x.X.x.x.x.X.x.',w:1},{s:'....X.......X...',w:1}]}},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C.......C.......',w:1},{s:'C...............',w:1}],
              lively: [{s:'C...c.u.C...c.u.',w:3},{s:'C...1.2.C...3.2.',w:2},{s:'C.1.2.3.C.1.2.3.',w:1}],
              rowdy: [{s:'C.1.c.u.C.1.c.u.',w:2},{s:'C.1.2.3.4.3.2.1.',w:1}]},
        fills: ['C...c.u.1.2.3.4.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...............',w:1}],
              lively: [{s:'R.......5.......',w:2},{s:'R.......5.....P.',w:1}],
              rowdy: [{s:'R...R...5....P..',w:1},{s:'R.......5...8...',w:1}]}},
    }},
  sea_shanty: {
    /* pirate rework per research: rolling swung 6/8, halyard one-pull-per-bar
       with the gang's clap answer, accordion bellows bed, fiddle croon,
       hemiola fills, extra human roughness */
    /* jaunty per Simone: Drunken Sailor bones — Dorian (the raised 6th is
       the sea-legs), i-bVII vamp, brisk roll */
    name: 'Saltbeard’s Shanty', icon: '⚓', mode: 'dorian', tonic: 4, bpm: 104,
    beatsPerBar: 2, stepsPerBeat: 6, swing: 0, lilt: .06, rough: 1.4,
    reverb: .16, drone: .3, pad: .05,
    sections: {A: [{d:0,q:'m'},{d:0,q:'m'},{d:6,q:'M'},{d:6,q:'M'}],
               B: [{d:0,q:'m'},{d:6,q:'M'},{d:0,q:'m'},{d:0,q:'m'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'shanty',
        pat: {calm: [{s:'S...........',w:2},{s:'S.....d.....',w:1}],
              lively: [{s:'S.....d.t.t.',w:2},{s:'S.t.t.d.....',w:1},{s:'S.....d..t..',w:1}],
              rowdy: [{s:'S.t.t.d.t.t.',w:2},{s:'S.....D.t.t.',w:1}]},
        fills: ['S.d.S.d.S.d.','D.d.D.d.D.d.']},
      claps: {kind:'drum', map:'shanty',
        pat: {lively: [{s:'......C.....',w:1}],
              rowdy: [{s:'......C.....',w:2},{s:'......C..c..',w:1}]}},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.3},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      squeeze: {kind:'gen', inst:'accordion', gen:'squeeze'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      pluck: {kind:'harmony', inst:'lute',
        pat: {calm: [{s:'C...........',w:1}],
              lively: [{s:'C.....c.....',w:2},{s:'C..u..c..u..',w:1},{s:'C.1.2.c.....',w:1}],
              rowdy: [{s:'C.c.u.C.c.u.',w:2},{s:'C.1.2.c..u..',w:1}]},
        fills: ['C.....4.3.2.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...........',w:1}],
              lively: [{s:'R.....5.....',w:2},{s:'R.........P.',w:1}],
              rowdy: [{s:'R.....5...P.',w:1},{s:'R..R..5.....',w:1}]}},
    }},
  greenwood_waltz: {
    name: 'Greenwood Waltz', icon: '🌿', mode: 'major', tonic: 7, bpm: 84,
    beatsPerBar: 3, stepsPerBeat: 4, swing: 0, reverb: .2, drone: .16, pad: .07,
    sections: {A: [{d:0,q:'M'},{d:5,q:'m'},{d:3,q:'M'},{d:4,q:'M'}],
               B: [{d:1,q:'m'},{d:4,q:'M'},{d:0,q:'M'},{d:4,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'d...........',w:1},{s:'............',w:1}],
              lively: [{s:'d...t...t...',w:2},{s:'d.t.t...t...',w:1},{s:'D...t...t.t.',w:1}],
              rowdy: [{s:'D...t...t.t.',w:2},{s:'D.t.t...t.t.',w:1},{s:'D...t.t.t.t.',w:1}]},
        fills: ['d...t...ttt.','D...ttt.t.t.']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.25},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      pluck: {kind:'harmony', inst:'harp',
        pat: {calm: [{s:'0...2...1...',w:1},{s:'0...1...2...',w:1}],
              lively: [{s:'0.1.2.3.4.3.',w:2},{s:'0.1.2.4.3.2.',w:2},{s:'0.2.1.3.2.4.',w:1}],
              rowdy: [{s:'0.1.2.3.4.5.',w:2},{s:'0.1.3.2.4.3.',w:1}]},
        fills: ['5.4.3.2.1.0.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...........',w:1}],
              lively: [{s:'R...........',w:2},{s:'R.......5...',w:1}],
              rowdy: [{s:'R...5...8...',w:1}]}},
    }},
  desert_caravan: {
    name: 'Desert Caravan', icon: '🐫', mode: 'hijaz', tonic: 2, bpm: 96,
    beatsPerBar: 4, stepsPerBeat: 4, swing: 0, reverb: .15, drone: .55, pad: 0,
    sections: {A: [{d:0,q:'M'},{d:0,q:'M'},{d:1,q:'M'},{d:0,q:'M'}],
               B: [{d:3,q:'m'},{d:1,q:'M'},{d:0,q:'M'},{d:0,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'darbuka',
        pat: {calm: [{s:'D.....T.D.......',w:1},{s:'D.......D...T...',w:1}],
              lively: [{s:'D.T.k.T.D.k.T.k.',w:3},{s:'D.T...T.D...T...',w:1},{s:'D.TkT.T.D.k.TkT.',w:2}],
              rowdy: [{s:'D.T.k.TkD.k.T.kT',w:2},{s:'D.TkkkT.D.kkT.kk',w:1},{s:'D.TkT.TkD.TkTkTk',w:1}]},
        fills: ['D.T...T.D.TkTkTk','D.T...TkTkTkD...','D.T.k.T.DkTkDkTk']},
      texture: {kind:'gen', inst:'darbuka', gen:'fingerTexture', density:.7},
      jingle: {kind:'jingle', inst:'riq', pat:{lively:[{s:'x...x...X...x...',w:1}], rowdy:[{s:'x.x.x.x.X.x.x.x.',w:1}]}},
      pluck: {kind:'harmony', inst:'oud',
        pat: {calm: [{s:'0.......0.......',w:1},{s:'0...............',w:1}],
              lively: [{s:'0...0.1.0...2.1.',w:2},{s:'0.0...1.0...1.2.',w:2}],
              rowdy: [{s:'0.0.0.1.0.0.2.1.',w:2},{s:'0.0.1.1.0.0.2.2.',w:1}]},
        fills: ['0.1.2.3.2.1.0...']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...............',w:1}],
              lively: [{s:'R.......R.......',w:2},{s:'R.......R.....P.',w:1}],
              rowdy: [{s:'R.......R...5...',w:1},{s:'R.......R.....P.',w:1}]}},
    }},
  mystic_grove: {
    name: 'Mystic Grove', icon: '🍄', mode: 'dorian', tonic: 9, bpm: 62,
    beatsPerBar: 2, stepsPerBeat: 6, swing: 0, reverb: .25, drone: .6, pad: .06,
    sections: {A: [{d:0,q:'m'},{d:0,q:'m'},{d:6,q:'M'},{d:6,q:'M'}],
               B: [{d:3,q:'M'},{d:3,q:'M'},{d:0,q:'m'},{d:0,q:'m'}]},
    form: 'AB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D...........',w:1},{s:'............',w:1}],
              lively: [{s:'D.....d.....',w:2},{s:'D.....d..t..',w:2},{s:'D..t..d.....',w:1}],
              rowdy: [{s:'D...t.d..t..',w:1},{s:'D.t...d.....',w:1}]},
        fills: ['D.....d.t.t.']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.15},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      pluck: {kind:'harmony', inst:'harp',
        pat: {calm: [{s:'0...2...4...',w:2},{s:'0...3...2...',w:1}],
              lively: [{s:'0...2.3.4...',w:2},{s:'0.1.2...4...',w:1}],
              rowdy: [{s:'0.1.2.3.4.5.',w:1},{s:'0.2.4.5.4.2.',w:1}]},
        fills: ['4...3...2...']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...........',w:1}],
              lively: [{s:'R.....5.....',w:1}],
              rowdy: [{s:'R.....5...P.',w:1}]}},
    }},
  willow_lament: {
    name: 'Willow Lament', icon: '🥀', mode: 'aeolian', tonic: 9, bpm: 72,
    beatsPerBar: 4, stepsPerBeat: 4, swing: 0, reverb: .27, drone: .45, pad: .07,
    sections: {A: [{d:0,q:'m'},{d:5,q:'M'},{d:2,q:'M'},{d:6,q:'M'}],
               B: [{d:3,q:'m'},{d:5,q:'M'},{d:0,q:'m'},{d:6,q:'M'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'celtic',
        pat: {calm: [{s:'D...............',w:2},{s:'................',w:1}],
              lively: [{s:'D.......d.......',w:2},{s:'D.......d...t...',w:2},{s:'D...t...d.......',w:1}],
              rowdy: [{s:'D...t...D...t...',w:2},{s:'D.t.t...d...t...',w:1}]},
        fills: ['D.......d...t.t.','D...t...d.t.d...']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.2},
      tss: {kind:'gen', inst:'silver', gen:'backbeatTss'},
      bowed: {kind:'gen', inst:'fiddle', gen:'bowedLine', octave:12},
      pluck: {kind:'harmony', inst:'harp',
        pat: {calm: [{s:'0...2...4...2...',w:2},{s:'0.......2.......',w:1}],
              lively: [{s:'0.1.2.3.4.3.2.1.',w:2},{s:'0...2.3.4...3.2.',w:2},{s:'0.1.2...4...2...',w:1}],
              rowdy: [{s:'0.1.2.3.4.5.4.3.',w:1},{s:'0.2.4.2.5.2.4.2.',w:1}]},
        fills: ['5.4.3.2.1.0.2.1.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...............',w:1}],
              lively: [{s:'R.......5.......',w:2},{s:'R.......5.....P.',w:1}],
              rowdy: [{s:'R.......5...P...',w:1},{s:'R...R...5.......',w:1}]}},
    }},
  deep_delve: {
    name: 'Deep-Delve March', icon: '⛏️', mode: 'phrygian', tonic: 11, bpm: 78,
    beatsPerBar: 4, stepsPerBeat: 4, swing: 0, reverb: .21, drone: .55, pad: .05,
    sections: {A: [{d:0,q:'5'},{d:1,q:'M'},{d:0,q:'5'},{d:6,q:'m'}],
               B: [{d:5,q:'M'},{d:1,q:'M'},{d:0,q:'5'},{d:0,q:'5'}]},
    form: 'AABB',
    parts: {
      drums: {kind:'drum', map:'march',
        pat: {calm: [{s:'S.......S.......',w:1}],
              lively: [{s:'S...t.d.S...t...',w:2},{s:'S...t...S..dt...',w:2},{s:'S.....d.S...t.d.',w:1}],
              rowdy: [{s:'S...t.d.S.d.t.d.',w:2},{s:'S.t.t.d.S.t.t.d.',w:1},{s:'S...t.dtS...tdtd',w:1}]},
        fills: ['S.....d.S.tdtdtd','S...t...Sdtdtdtd']},
      texture: {kind:'gen', inst:'bongos', gen:'fingerTexture', density:.3},
      pluck: {kind:'harmony', inst:'oud',
        pat: {calm: [{s:'C...............',w:1}],
              lively: [{s:'C.......c.......',w:2},{s:'C.......C.....u.',w:1}],
              rowdy: [{s:'C...c...C...c.u.',w:2},{s:'C...c...C...c...',w:1}]},
        fills: ['C.......0.1.0.1.']},
      bass: {kind:'bass', inst:'bassViol',
        pat: {calm: [{s:'R...............',w:1}],
              lively: [{s:'R.......R.......',w:2},{s:'R.......R.....P.',w:1}],
              rowdy: [{s:'R...R...R...R...',w:1}]}},
    }},
};

/* boot-time sanity: warn on any pattern string whose length ≠ steps per
   bar, and on parts pointing at unknown generators/maps */
export function validateStyles(generators) {
  for (const [id, sty] of Object.entries(STYLES)) {
    const n = sty.beatsPerBar * sty.stepsPerBeat;
    for (const [pn, part] of Object.entries(sty.parts)) {
      for (const arr of Object.values(part.pat || {})) for (const v of arr)
        if (v.s.length !== n) console.warn('BAD PATTERN LEN', id, pn, v.s, v.s.length, 'expected', n);
      for (const f of part.fills || []) if (f.length !== n) console.warn('BAD FILL LEN', id, pn, f);
      if (part.kind === 'gen' && !generators[part.gen]) console.warn('BAD GEN', id, pn, part.gen);
      if (part.kind === 'drum' && !DRUM_MAPS[part.map]) console.warn('BAD MAP', id, pn, part.map);
    }
  }
}
